### ISSUE TITLE
Run on Android

### ISSUE THREAD

**Issue by alitalibiq** [MrSPD-2703/ESP_For_PubgMobile#2]
Hi brother
Is this application for Android?
Is it completely free?
Does it work with a no root?
Do you have a channel or group on the following, or independent?
Thank you

**Comment by nitesh030923** [comment]
It is for android.
it requires root access.
thank you

**Comment by MrSPD-2703** [comment]
Hello dear,
Yes this application is for Android device but requires root.
This ESP has been developed only for educational purpose and hence it's free!!!.
Coming to your last question , I have a channel called INCODERS in telegram , you can check out for more stuffs.
You can contact me through Gmail : spd.doddini@gmail.com
Thank you stay peace✌️
